#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ORG_DIR="/YOUR/WORKSPACE/DIR"
SOURCE_CLAUDE="$CONFIG_DIR/CLAUDE.md"
ORG_CLAUDE="$ORG_DIR/CLAUDE.md"
ORG_AGENTS="$ORG_DIR/AGENTS.md"
ORG_GEMINI="$ORG_DIR/GEMINI.md"
CONFIG_AGENTS="$CONFIG_DIR/AGENTS.md"
CONFIG_GEMINI="$CONFIG_DIR/GEMINI.md"
ORG_CURSOR_RULES="$ORG_DIR/.cursor/rules"
ORG_CURSOR_RULE="$ORG_CURSOR_RULES/org-agent-instructions.mdc"

cp -f "$SOURCE_CLAUDE" "$ORG_CLAUDE"
mkdir -p "$ORG_CURSOR_RULES"

python3 - "$SOURCE_CLAUDE" "$ORG_CLAUDE" "$ORG_AGENTS" "$CONFIG_AGENTS" "$ORG_GEMINI" "$CONFIG_GEMINI" "$ORG_CURSOR_RULE" <<'PY'
from pathlib import Path
import sys

source = Path(sys.argv[1])
org_claude = Path(sys.argv[2])
org_agents = Path(sys.argv[3])
config_agents = Path(sys.argv[4])
org_gemini = Path(sys.argv[5])
config_gemini = Path(sys.argv[6])
org_cursor_rule = Path(sys.argv[7])

def shim(target: Path, canonical: Path, output_file: Path) -> str:
    return "\n".join([
        "<!-- AUTO-GENERATED by /YOUR/WORKSPACE/DIR/agent-config/scripts/sync-org-agent-instructions.sh.",
        f"     Source of truth: {canonical}.",
        f"     {output_file.name} is a compatibility shim for tools that do not load CLAUDE.md directly.",
        "     Do not edit this generated file directly. -->",
        "",
        "# Agent Instructions Shim",
        "",
        f"The canonical instructions for this directory live in `{target}`.",
        "",
        "Before multi-step or shared-state work, read that `CLAUDE.md` file and follow it as the source of truth.",
        "If your tool does not automatically expand `@/absolute/path` imports, read each imported file manually before acting on those instructions.",
        "",
        "Do not duplicate or edit instructions here. Edit the canonical `CLAUDE.md` source and rerun the sync script.",
        "",
    ]) + "\n"

org_agents.write_text(shim(org_claude, source, org_agents))
config_agents.write_text(shim(source, source, config_agents))
org_gemini.write_text(shim(org_claude, source, org_gemini))
config_gemini.write_text(shim(source, source, config_gemini))

org_cursor_rule.write_text("\n".join([
    "---",
    "description: Riddim org agent instructions",
    "alwaysApply: true",
    "---",
    "",
    "<!-- AUTO-GENERATED by /YOUR/WORKSPACE/DIR/agent-config/scripts/sync-org-agent-instructions.sh.",
    f"     Source of truth: {source}.",
    "     Do not edit this generated file directly. -->",
    "",
    f"Follow the canonical org instructions in `{org_claude}` before doing multi-step or shared-state work.",
    "",
    "Do not mention AI co-authorship, collaboration, assistance, or generation in commits, PR descriptions, PR comments, issue comments, release notes, changelogs, file headers, docs, or other project artifacts unless the user explicitly asks for that disclosure in that specific artifact.",
    "",
    "Never add trailers or prose such as `Co-authored-by: Claude`, `Generated with Codex`, `Implemented with Gemini`, `Built by Cursor`, or similar references to AI tools, models, assistants, editors, or agents. Keep artifact authorship focused on the human or bot identity required by the repository workflow.",
    "",
]))
PY

echo "Synced org agent instructions:"
echo "  copied:   $SOURCE_CLAUDE -> $ORG_CLAUDE"
echo "  shimmed:  $ORG_CLAUDE -> $ORG_AGENTS"
echo "  shimmed:  $SOURCE_CLAUDE -> $CONFIG_AGENTS"
echo "  shimmed:  $ORG_CLAUDE -> $ORG_GEMINI"
echo "  shimmed:  $SOURCE_CLAUDE -> $CONFIG_GEMINI"
echo "  shimmed:  $ORG_CLAUDE -> $ORG_CURSOR_RULE"
